### ISSUE TITLE
[feature request]  hiprand support

### ISSUE THREAD

**Issue by zjin-lcf** [CHIP-SPV/chipStar#107]
It may be useful to support a HIP program with hiprand() functions on an Intel GPU.

**Comment by pvelesko** [comment]
Do you have specific apps in mind which use hiprand?

**Comment by pvelesko** [comment]
@zjin-lcf

**Comment by pvelesko** [comment]
Also required by AMReX

**Comment by pvelesko** [comment]
@zjin-lcf @jz10

I got have rocRAND compiled, what application did you need it for?

**Comment by pvelesko** [comment]
rocRAND was implemented but needs testing and an application.

**Comment by zjin-lcf** [comment]
The applications may be https://github.com/ROCm/rocRAND/blob/develop/benchmark/
