### ISSUE TITLE
CMake generated hip-config enforces the use of clang for downstream objects

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#340]
- [ ] Add a test

```
CMake Error at /home/pvelesko/install/HIP/chip-spv/lib/cmake/hip/hip-config.cmake:143 (message):
  this project must be compiled with clang.  CMAKE_CXX_COMPILER_ID = GNU
Call Stack (most recent call first):
  CMakeLists.txt:126 (find_package)
```

**Comment by pvelesko** [comment]
I think the only case where we don't need to have this enforced is the case where you're compiling in C mode and just using the headers with no actual offload. If so, I'll probably just close this ticket because it would be too much effort for little reward 

@pjaaskel  @linehill

**Comment by linehill** [comment]
AMD supports C compiler for HIP API only use cases: "Use the HIP API without compiling the GPU device code. As there is no GPU code, any C or C++ compiler can be used. The find_package(hip) provides the hip::host target to use HIP in this context". [Source](https://docs.amd.com/bundle/Using-CMake-with-ROCm/page/Using_CMake_with_ROCm.html).

**Comment by pvelesko** [comment]
any suggestions on how to do this?

Somehow the compiler check must execute only if the parent cmake links against `hip::device` target. Struggling to come up with a simple solution.
