### ISSUE TITLE
 SPV_INTEL_fp_fast_math_mode used without declaring it as an extension in the SPIR-V

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chipStar#429]
This is reproducible on many SPIR-Vs, a reporter told. Is it a bug in the LLVM translator?

**Comment by pjaaskel** [comment]
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2028

**Comment by linehill** [comment]
Dropped from Milestone 1.0: resolution depends on external issue.

**Comment by pjaaskel** [comment]
This fix is in upstream now.

**Comment by karolherbst** [comment]
This is still an issue using the recommended LLVM fork via `./scripts/configure_llvm.sh`

**Comment by karolherbst** [comment]
But this issue also opens up the questions of how one can reliably use `SPV_INTEL_fp_fast_math_mode` as there is no CL extension adding this SPIRV extension, so nothing can rely on it being supported in the first place.

**Comment by linehill** [comment]
> This is still an issue using the recommended LLVM fork via ./scripts/configure_llvm.sh

On what LLVM version this happens? Could you send us / point us to the HIP source that produces the Intel fast math code?

**Comment by karolherbst** [comment]
> > This is still an issue using the recommended LLVM fork via ./scripts/configure_llvm.sh
> 
> On what LLVM version this happens? Could you send us / point us to the HIP source that produces the Intel fast math code?

mhh, seems to be on 6009708b4367171ccdbf4b5905cb6a803753fe18 but it also seems to be upstream LLVM. I thought the script is cloning some fork with a bunch of patches on it? I invoked it with `./scripts/configure_llvm.sh 17 /home/kherbst/local-chip/ dynamic on`

**Comment by karolherbst** [comment]
fyi: I validate each incoming SPIR-V inside rusticl, so that's where that error is coming from.

**Comment by linehill** [comment]
> mhh, seems to be on 6009708b4367171ccdbf4b5905cb6a803753fe18 but it also seems to be upstream LLVM.

To me it seems that the configure_llvm.sh does not do as advertised in the README.md and installs the upstream LLVM instead of chipStar's fork of it.

**Comment by karolherbst** [comment]
> > mhh, seems to be on 6009708b4367171ccdbf4b5905cb6a803753fe18 but it also seems to be upstream LLVM.
> 
> To me it seems that the configure_llvm.sh does not do as advertised in the README.md and installs the upstream LLVM instead of chipStar's fork of it.

yeah, seems you are right. Guess I'll need to hack around it locally for now, but don't know when I'll find time this week for another round of testing. Would be helpful if one could fix it in the meantime.

**Comment by pvelesko** [comment]
> configure_llvm.sh does not do as advertised in the README.md and installs the upstream LLVM instead of chipStar's fork of it

this was resolved. Please re-open if the issue persists.
