### ISSUE TITLE
CHIP-SPV is rentering it's exported APIs

### ISSUE THREAD

**Issue by Kerilk** [CHIP-SPV/chipStar#485]
As can be seen on this image, CHIP-SPV is calling it's exported dynamic API symbols. This can be very problematic, especially if these symbols have been intercepted and their behavior modified. CHIP-SPV should call internal symbols that are not exported.

![image](https://github.com/CHIP-SPV/chip-spv/assets/1815142/0dd37a75-64ba-414e-afcd-cb781fc359f2)

**Comment by pvelesko** [comment]
is this made with your profiling tool?

**Comment by pvelesko** [comment]
is this made with your profiling tool?

**Comment by Kerilk** [comment]
Yes
