### ISSUE TITLE
Warning in hipConfigureCall

### ISSUE THREAD

**Issue by Kerilk** [CHIP-SPV/chipStar#494]
The following code generates a warning:
https://github.com/CHIP-SPV/chip-spv/blob/c83cd725998107d62f37e57cc53dadf87db0ada1/src/CHIPBindings.cc#L4043-L4052
It seems `ChipQueue` should be used instead of `Stream` in:
https://github.com/CHIP-SPV/chip-spv/blob/c83cd725998107d62f37e57cc53dadf87db0ada1/src/CHIPBindings.cc#L4049

If it is indeed the case, I can add it to:
https://github.com/CHIP-SPV/chip-spv/pull/493

**Comment by pvelesko** [comment]
That's correct, add it.
