### ISSUE TITLE
Math function pow() call not supported on device

### ISSUE THREAD

**Issue by jjennychen** [CHIP-SPV/chipStar#498]
When I called the pow() function and run it with CHIP-SPV, there was an error `reference to __host__ function 'pow' in __host__ __device__ function`... I was expecting pow() or other math functions to be supported on devices, maybe CHIP-SPV hasn't implemented it yet?

Here are the steps to reproduce the error:
1. Log into JLSE
2. Get an iris node with the command `qsub -I -n 1 -q iris -t 360` (we are using iris as the example here)
3. After getting the node, load the modules with:
```
module use /soft/modulefiles
module purge
module load intel_compute_runtime
module load chip-spv
```
4. Create a test.cu file and put the following code:
```
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <hip/hip_runtime.h>

__global__ 
void kernel()
{
  double result = pow(2.0, 2.0);
}

int main(int argc, char* argv[])
{
  hipLaunchKernelGGL(kernel, (100+255)/256, 256, 0, 0);

  return 0;
}
```
5. Compile with the following command:
`hipcc -std=c++14 -Wall -I../vanGenuchten-cuda test.cu -o test`
6. Expected to see an error: `reference to __host__ function 'pow' in __host__ __device__ function` for the pow function

**Comment by pvelesko** [comment]
This is caused by 
```
#include <math.h>
```

For some reason makes it pick up host side pow, fails it as a candidate, and doesn't check further headers.
