### ISSUE TITLE
volatile array in device-side memset (performance issue)

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/chipStar#550]
With @jjennychen, we noticed that the device-side memset for CHIP-SPV was much slower than writing our own loop to do a memset. With @pengtu we narrowed this down to the fact that the array in memset (and memcpy) is declared as volatile (https://github.com/CHIP-SPV/chipStar/blob/96d21716110212530f663342c9ab214b9b866061/bitcode/devicelib.cl#L446).

Is there a reason this is volatile? I can't think of why we would need that for the memset, but I could be missing something. When we tested without the volatile, we saw much better performance.

Thanks!

**Comment by pjaaskel** [comment]
(FWIW: I don't see a reason.)
