### ISSUE TITLE
Missing namespace cooperative_groups

### ISSUE THREAD

**Issue by sohamsgh** [CHIP-SPV/chipStar#574]
For building ExaBiome, we need the namespace cooperative_groups, which exists in nvidia and amd backends. However we observed that the contents of the [file](https://github.com/CHIP-SPV/chipStar/blob/main/include/hip/spirv_hip_cooperative_groups.h) are commented out for the spirv backend. Is there a plan to support this?

We get the following error: 

```shell 
hipcc --std=c++11 -O3 -I. -c kernel.cpp -o ./build/kernel.o
kernel.cpp:5:17: error: expected namespace name
using namespace cooperative_groups;
                ^
```

**Comment by pjaaskel** [comment]
Which features of CGs are used by Exabiome?

**Comment by sohamsgh** [comment]
Sorry about this, found out that ExaBiome in its present form doesn't use CG, its there for possible future use.
