### ISSUE TITLE
GitHub Issues are disabled on dependency repositories owned by CHIP-SPV

### ISSUE THREAD

**Issue by JayFoxRox** [CHIP-SPV/chipStar#603]
Missing GitHub issues on:

- https://github.com/CHIP-SPV/HIP
- https://github.com/CHIP-SPV/HIPCC
- https://github.com/CHIP-SPV/llvm-project
- https://github.com/CHIP-SPV/SPIRV-LLVM-Translator

That makes it hard to report bugs or suggest features.

**Comment by pjaaskel** [comment]
Issues enabled. Thanks for noticing.
