### ISSUE TITLE
[HIPCC] error: no such file or directory: 'pp'

### ISSUE THREAD

**Issue by linehill** [CHIP-SPV/chipStar#621]
Odd things happen if you feed files only differing by their extension:
```
$ $ ../install/bin/hipcc -x hip foo.cpp foo.c
clang-15: error: no such file or directory: 'pp'

failed to execute:/mnt/md1/linehill/ws-chipstar-2/install/bin/clang++ -L/mnt/md1/linehill/ws-chipstar-2/install/lib -lCHIP -Wl,-rpath,/mnt/md1/linehill/ws-chipstar-2/install/lib -I//mnt/md1/linehill/ws-chipstar-2/install/include  -x hip pp  -D__HIP_PLATFORM_SPIRV__= --offload=spirv64 -Xclang -no-opaque-pointers -nohipwrapperinc --hip-path=/mnt/md1/linehill/ws-chipstar-2/install --target=x86_64-unknown-linux-gnu -include /mnt/md1/linehill/ws-chipstar-2/install/include/hip/spirv_fixups.h -x c foo.c foo.c -D__HIP_PLATFORM_SPIRV__ -isystem /mnt/md1/linehill/ws-chipstar-2/install/include
```

ROCm's hipcc succeeds to run the command:
```
$ hipcc --version
HIP version: 5.3.22061-e8e78f1a
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.3.0 22362 3cf23f77f8208174a2ee7c616f4be23674d7b081)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.3.0/llvm/bin
$ hipcc -x hip foo.cpp foo.c
$ echo $?
0
```

**Comment by linehill** [comment]
FYI, another case:
```
$ ../install/bin/hipcc main.o foo.cu_o bar.hip_o
clang-15: error: no such file or directory: '_o'
clang-15: error: no such file or directory: '_o'
clang-15: error: no such file or directory: 'foo.cu'
clang-15: error: no such file or directory: 'bar.hip'
...
```

**Comment by pvelesko** [comment]
Yeah I'm working on this right now. -x option is quite problematic. If I understand correctly, this is legal:
```
clang++ -x hip src.aaa -x c++ src.bbb -x c src.ccc
```

You can specify -x option multiple times and it applies to the source files following -x correct?

**Comment by pjaaskel** [comment]
Maybe a stupid question without looking at the implementation: Why are we parsing these options in detail and not just mostly passing them to clang++ as is, perhaps manipulating the cmdline string a bit before?

**Comment by pvelesko** [comment]
Because we need to determine when to add SPIR-V compilation flags. I adopted this from HIPAMD's hipcc the original intention being to not deviate too far from theirs. Honestly, it's been working fine for me so I only did the bare minimum to fix whatever small issue popped up.

**Comment by pjaaskel** [comment]
Breaks also here. Shall we disable the test until the problem fixed or what's the plan with this?

**Comment by pvelesko** [comment]
What test is breaking for you? I thought this was resolved for the time being (until hipcc refactor) @pjaaskel

**Comment by pjaaskel** [comment]
> What test is breaking for you? I thought this was resolved for the time being (until hipcc refactor) @pjaaskel

TestHipcc621.bash was failing, but it could be because I had an older hipcc in PATH. Are the bash tests using the build directory binaries? Do we add the build bin dir first in the PATH before executing them?

**Comment by pvelesko** [comment]
> Are the bash tests using the build directory binaries? 

yes

**Comment by pjaaskel** [comment]
OK. Then I do not know why it failed for me initially. Well, works now!
