### ISSUE TITLE
[CI] Building issues

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#636]
```
Err:9 https://apt.repos.intel.com/oneapi all InRelease
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Reading package lists...
W: GPG error: https://apt.repos.intel.com/oneapi all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
E: The repository 'https://apt.repos.intel.com/oneapi all InRelease' is not signed.
Error: Process completed with exit code 100.
```

**Comment by Kerilk** [comment]
Is this still an issue or a fluke on on Intel side?

**Comment by pvelesko** [comment]
Consistent failures. Something about keys

**Comment by Kerilk** [comment]
doesn't seem to be consistent, these passed: https://github.com/CHIP-SPV/chipStar/actions/runs/6379942163

**Comment by Kerilk** [comment]
Reran: https://github.com/CHIP-SPV/chipStar/actions/runs/6378924693/job/17321966498
Now passing. So I would say fluke on Intel's side, outdated certificate maybe?

**Comment by pvelesko** [comment]
Oh ok it was failing all day today it seemed like.
