### ISSUE TITLE
Potential race in SyncQueues

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#642]
```
  auto EventsToWaitOn = getSyncQueuesLastEvents();
  // Every event in EventsToWaitOn should have a dependency on MemCopyEvent so
  // that they don't get destroyed before MemCopyEvent
  for (auto &Event : EventsToWaitOn) {
    LOCK(Event->EventMtx);
    std::static_pointer_cast<CHIPEventLevel0>(Event)->addDependency(
        TargetEvent);
  }
```

It's possible that `LastEvent` for one of the active queues can change by the time we enter enter loop, but I am not convinced that this is an issue? Maybe we can discuss in further detail here

**Comment by pjaaskel** [comment]
If there will be new "lastevents" the EventsToWaitOn will be the old ones and the new commands might finish later.

**Comment by pvelesko** [comment]
yes I agree that this scenario can happen but I don't see why that is an issue. If you are submitting things things multiple threads to multiple queues, aren't you responsible yourself for ensuring that commands are submitted in the correct order?

**Comment by pjaaskel** [comment]
Yes, that's right, but not sure if the logic works here correctly. If you use "Lastevent" info to implement a barrier and if the lastevent info is not protected by other queues, it moves around and you might end up waiting on an event you are not supposed to wait (at the position where the barrier was enqueued). (I'm not sure if this is happening here or not).
