### ISSUE TITLE
use of overloaded operator is ambiguous

### ISSUE THREAD

**Issue by zjin-lcf** [CHIP-SPV/chipStar#647]
hipcc is from ROCm.  Please see the following message.

```
hipcc hipComplex.cc (chipStar/samples/hipComplex)

hipComplex.cc:8:5: error: use of overloaded operator '*=' is ambiguous (with operand types 'hipDoubleComplex' (aka 'HIP_vector_type<double, 2>') and 'hipDoubleComplex')
  y *= x;
  ~ ^  ~
/opt/rocm-5.4.0/include/hip/amd_detail/amd_hip_vector_types.h:838:26: note: candidate function
        HIP_vector_type& operator*=(const HIP_vector_type& x) noexcept
```

**Comment by zjin-lcf** [comment]
Would you rewrite the operators as, for example, hipCmul(x,y) ?

**Comment by Kerilk** [comment]
@linehill Any idea why our sample would not compiler on rocm 5.4? Seems correct HP code to me.

**Comment by linehill** [comment]
It's most likely a bug in their headers. There is a same issue but for hipFloatComplex instead here: https://github.com/ROCm-Developer-Tools/HIP/issues/2797.

**Comment by zjin-lcf** [comment]
@Kerilk  @linehill  Thanks.
