### ISSUE TITLE
HeCBench: chacha20-hip validation failure

### ISSUE THREAD

**Issue by kballeda** [CHIP-SPV/chipStar#666]
**Benchmark:** chacha20-hip
**Log:** 
./main 100000
Average execution time of kernels: 244.002747 (us)
FAIL

Currently Loaded Modules:
  1) mpich/icc-all-pmix-gpu/51.2   3) cray-libpals/1.2.12   5) craype-x86-spr           7) oneapi-testing/2023.2.003.PUBLIC
  2) libfabric/1.15.2.0            4) cray-pals/1.2.12      6) perftools-base/22.09.0   8) graphics-compute-runtime/agama-ci-devel-704.30

**Comment by pvelesko** [comment]
Fixed as of chipStar-v1.2
