### ISSUE TITLE
HeCBench: keogh-hip validation failure

### ISSUE THREAD

**Issue by kballeda** [CHIP-SPV/chipStar#669]
**Benchmark:** keogh-hip

**Log:**
kballeda@x1002c6s4b0n0:~/ANL_WORK/09_enable_more/src/keogh-hip> make run
hipcc  -std=c++14 -Wall -I../keogh-cuda -O3 -c main.cu -o main.o

hipcc  -std=c++14 -Wall -I../keogh-cuda -O3 main.o -o main

./main 256 20000000 100
Query length = 256
Subject length = 20000000
Average kernel execution time: 0.011092 (s)
4 29901.982422 29901.980469
FAIL
 
**Driver:** - graphics-compute-runtime/agama-ci-devel-704.30

**Comment by pvelesko** [comment]
Fixed as of chipStar-v1.2
