### ISSUE TITLE
HeCBench: randomAccess-hip validation failure

### ISSUE THREAD

**Issue by kballeda** [CHIP-SPV/chipStar#670]
**Benchmark:** randomAccess-hip 

**Log:**
./main 10
Table size = 67108864
Main table size   = 2^26 = 67108864 words
Number of updates = 268435456
Average kernel execution time: 0.305855 (s)
Found 65817629 errors in 67108864 locations (FAIL).
make: *** [Makefile:55: run] Error 1

**Driver:** - graphics-compute-runtime/agama-ci-devel-704.30

**Comment by pvelesko** [comment]
Fixed as of chipStar-v1.2
