### ISSUE TITLE
Skipping uninit via CHIP_SKIP_UNINIT results in various segfaults 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#749]
```
The following tests FAILED:
	671 - Unit_hipMemsetFunctional_ZeroSize_3D (SEGFAULT)
	826 - Unit_hipStreamPerThread_MultiThread (SEGFAULT)
	827 - Unit_hipStreamPerThread_DeviceReset_1 (SEGFAULT)
	837 - Unit_hipClassKernel_Friend (SEGFAULT)
	854 - sincospifSpotTest (SEGFAULT)
	858 - syncthreadsExitedThreads (SEGFAULT)
	894 - TestRecordEventBlocking (SEGFAULT)
	909 - TestForgottenModuleUnload (Failed)
```

**Comment by pvelesko** [comment]
Is `CHIP_SKIP_UNINIT` still needed? @linehill

**Comment by linehill** [comment]
Considering the reason it was added for (from chipStar_1.1.rst):
```
certain combinations of drivers, hardware and OpenCL backend causes
chipStar to crash at exit. As a workaround, the user can set the CHIP_SKIP_UNINIT 
env variable to skip the uninitialization of the chipStar library.
```
Seems like we might still need it.

**Comment by pvelesko** [comment]
I think you added this options @franz  do you remember which platform needed it?

**Comment by franz** [comment]
Yeah it was PVC with particular OpenCL driver versions. IIRC unfortunately it was the older drivers that worked and newer drivers that crashed. But i haven't tested on PVC in a few months so maybe it's fixed now.

**Comment by pvelesko** [comment]
Skipping uninitialization doens't seem to be needed on any of the systems that I've tested.
