### ISSUE TITLE
Why we don't account the tail padding when compute a arg'size?

### ISSUE THREAD

**Issue by joyongzhu** [CHIP-SPV/chipStar#860]
I came across a problem and was very confused:

I got an incorrect arg‘s size in this code because it didn't take into account the tail filling , I would like to know why this is done?

src/spirv.cc:439
```
        // Compute actual size as in spv::Op::OpTypeArray branch
        // except don't account the tail padding. C analogy as
        // example: 'struct { char a; int b; char c}' takes 9 bytes.
        size_t MemberAlignment = Type->alignment();
        TotalSize = roundUp(TotalSize, MemberAlignment);
        TotalSize += Type->size();
        if (MemberAlignment > MaxAlignment)
          MaxAlignment = MemberAlignment;
```

**Comment by linehill** [comment]
> I would like to know why this is done?

I recall, it's for the same reason: getting kernel argument sizes correct. Accounting the tail padding on structs caused errors on kernel setter calls. Perhaps, this is a driver specific issue? 

Could you post more details about your environment and the program  (chipStar backend used, driver being used, debug logs)? Could you post us a HIP source (preferably a reduced one) that triggers the issue?

**Comment by joyongzhu** [comment]
> I recall, it's for the same reason: getting kernel argument sizes correct. Accounting the tail padding on structs caused errors on kernel setter calls. Perhaps, this is a driver specific issue?

It can be know, the current code is fine on the Intel platform, so I suspect it has something to do with the GPU driver.

For some special reasons, I can't provide more details about this undisclosed GPU.

But your response has been a huge help to me, and if I feel that my changes will benefit the current project, I will try to submit some optimizations to the project.
