### ISSUE TITLE
Can't find declaration for hipLaunchKernel_spt

### ISSUE THREAD

**Issue by joyongzhu** [CHIP-SPV/chipStar#915]
I compile a test with "-fgpu-default-stream=per-thread"，but a compilation error occurred:
```
streamperthread/hipStreamPerThrdCompilerOptn.cc:50:17: error: Can't find declaration for hipLaunchKernel_spt
__global__ void DefltStrmPT_Square(int64_t *C_d, int64_t N) {
                ^
1 error generated when compiling for host.
```

I found that the compiler would require the code to use **hipLaunchKernel_spt**, and this function declared in **spirv_spt.h**，
should I manually include this header file into the source code of the test program?
![image](https://github.com/user-attachments/assets/235b7680-6754-409c-9215-18bffedbc22c)

**Comment by pvelesko** [comment]
@joyongzhu please test #916 

don't forget to `git submodule update` after you checkout the branch

**Comment by joyongzhu** [comment]
it work ~~~ thanks ~~~
![image](https://github.com/user-attachments/assets/511da1e5-0cbb-4dc9-83f3-d9f20d094dcf)
