### ISSUE TITLE
CHIP_JIT_FLAGS_OVERRIDE has no effect

### ISSUE THREAD

**Issue by thirtythreeforty** [CHIP-SPV/chipStar#929]
The following logic incorrectly ensures that `JitFlags_` is always set to the default:

https://github.com/CHIP-SPV/chipStar/blob/840882dd7e783c35d81f49395ba01cb85075a7e8/src/CHIPDriver.hh#L233

https://github.com/CHIP-SPV/chipStar/blob/840882dd7e783c35d81f49395ba01cb85075a7e8/src/CHIPDriver.hh#L287

https://github.com/CHIP-SPV/chipStar/blob/840882dd7e783c35d81f49395ba01cb85075a7e8/src/CHIPDriver.hh#L306-L311

May I also suggest that simply _setting_ `CHIP_JIT_FLAGS_OVERRIDE` to anything, even the empty string, should cause it to override. Currently the string must be non-empty to override.

**Comment by pvelesko** [comment]
draft pr https://github.com/CHIP-SPV/chipStar/pull/931
