### ISSUE TITLE
Build failure on distros with dynamically linked LLVM

### ISSUE THREAD

**Issue by thirtythreeforty** [CHIP-SPV/chipStar#930]
On Arch Linux, I get the following build failure:

```
$ VERBOSE=1 make
[ 10%] Linking CXX executable prepare-builtins
cd /.../chipStar/build/bitcode/ROCm-Device-Libs/utils/prepare-builtins && /usr/bin/cmake -E cmake_link_script CMakeFiles/prepare-builtins.dir/link.txt --verbose=1
/usr/bin/clang++  -Wno-duplicate-decl-specifier -Wno-tautological-constant-compare  -Wno-c++20-extensions -Wno-unused-result -Wno-delete-abstract-non-virtual-dtor -Wno-deprecated-declarations -Wunused-command-line-argument -gdwarf-4 --gcc-toolchain=/usr -O2 -g -DNDEBUG "CMakeFiles/prepare-builtins.dir/prepare-builtins.cpp.o" -o prepare-builtins  /usr/lib/libLLVMSupport.a -lLLVMCore -lLLVMBitReader -lLLVMBitWriter -lrt -ldl -lm /usr/lib/libz.so /usr/lib/libzstd.so.1.5.6 /usr/lib/libtinfo.so /usr/lib/libLLVMDemangle.a
/usr/bin/ld: cannot find -lLLVMCore: No such file or directory
/usr/bin/ld: cannot find -lLLVMBitReader: No such file or directory
/usr/bin/ld: cannot find -lLLVMBitWriter: No such file or directory
```

Some Googling indicates that this is due to ROCm's (mis?)use of LLVM CMake helpers, as pointed out in https://github.com/ROCm/HIPIFY/issues/1397 which was uncharitably closed with "your distro is unsupported":

>This is because on Arch the LLVM libraries are compiled with LLVM_LINK_LLVM_DYLIB=ON to one shared library llvm.so instead of multiple static ones.
>The same goes for clang.
>
>For LLVM it is recommended in https://github.com/llvm/llvm-project/issues/34593 to use the "llvm_config" macro to get the correct library names for a list of modules.

The following patch to chipStar's ROCm-Device-Libs fixes this error:

```diff
diff --git a/utils/prepare-builtins/CMakeLists.txt b/utils/prepare-builtins/CMakeLists.txt
index 981d422..b3cf9a3 100644
--- a/utils/prepare-builtins/CMakeLists.txt
+++ b/utils/prepare-builtins/CMakeLists.txt
@@ -26,6 +26,4 @@ set_target_properties(prepare-builtins PROPERTIES
   CXX_STANDARD 17
   CXX_STANDARD_REQUIRED Yes
   CXX_EXTENSIONS No)
-llvm_update_compile_flags(prepare-builtins)
-llvm_map_components_to_libnames(llvm_libs support core bitreader bitwriter)
-target_link_libraries(prepare-builtins ${llvm_libs})
+llvm_config(prepare-builtins USE_SHARED support core bitreader bitwriter)
```

I am not certain what you want to do with this, since upstream has moved their device libs into LLVM. But I'm hoping it can at least add to the Googleability of this problem!

**Comment by pvelesko** [comment]
https://github.com/CHIP-SPV/ROCm-Device-Libs/pull/3 
https://github.com/CHIP-SPV/chipStar/pull/932

**Comment by pvelesko** [comment]
@thirtythreeforty Can you confirm that #932 fixes your issue?

**Comment by thirtythreeforty** [comment]
Works for me!
